Algoritmo "maior número"

Var
N1,n2,n3 : real
num : caracter

Inicio

escreval ("Digite 3 Números :")
escreval
escreval
escreval ("Digite um numero :")
leia (n1)
escreval ("Digite um numero :")
leia (n2)
escreval ("Digite um numero :")
leia (n3)

escreval ("o maior número foi :")

se (n1>n2) e (n1>n3) entao
escreval (n1)
fimse
se (n2>n1) e (n2>n3) entao
escreval (n2)
fimse
se (n3>n1) e (n3>n2) entao
escreval (n3)
fimse
fimalgoritmo